
title: Astrid Farmer
description: > #
  I'm a final year student at The University of Queensland, with a knack for web design,
  software development, and messing around with electronics.
baseurl: /
url: "" 

email: astridfarmer1@gmail.com
github: "https://github.com/astridf"
github-username: astridf
dribbble: "https://dribbble.com/astridfarmer"
dribbble-username: astridfarmer
linkedin: "https://au.linkedin.com/in/astridfarmer"
linkedin-username: astridfarmer
twitter: "https://twitter.com/astrid_farmer"
twitter-username: astrid_farmer
codepen: "http://codepen.io/astridfarmer/"
codepen-username: astridfarmer
instagram: "https://www.instagram.com/astrid_farmer/"
instagram-username: astrid_farmer

collections:
  posts:
    permalink: /blog/:title
  projects:
    output: true
    layout: projectpage
    permalink: /:path/

# Build settings
markdown: kramdown
